export BASE_IMAGE="vauxoo/odoo-150-image"
export DOCKER_IMAGE_REPO="quay.io/vauxoo/l10n_edi_deactivate_sh"
export PSQL_VERSION="11"
export VERSION="15.0"
export ODOO_REPO="vauxoo/odoo"
export ODOO_BRANCH="15.0"
export MAIN_APP="l10n_edi_deactivate_sh"
export TRAVIS_PYTHON_VERSION="3.8"
export TRAVIS_REPO_SLUG="Vauxoo/"
export COUNTRY="CR"
export CUSTOMER="l10n_edi_deactivate_sh"
export COVERAGE_MIN=80
export COVERAGE_PRECISION=2
export INSTALL_OPTIONS="--init=l10n_cr_edi"
