# Copyright 2019 Vauxoo
# License AGPL-3 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "Instance Creator",
    "summary": """
    Instance creator for edicionesfiscales. This is the app.
    """,
    "author": "Vauxoo",
    "website": "https://www.vauxoo.com",
    "license": "LGPL-3",
    "category": "Installer",
    "version": "15.0.1.0.7",
    "depends": [
        "account_edi_ubl",
        "account_accountant",
        "google_account",
        "hr_contract",
        "hr_work_entry",
        "l10n_mx_edi_extended",
        "l10n_mx_edi_product_refund_accounts",
        "l10n_mx_edi_purchase_document",
        "mail_group",
        "mrp_workorder",
        "partner_vat_unique",
        "stock_no_negative",
        "theme_default",
        "website_sale",
    ],
    "test": [],
    "data": [
        "security/ir.model.access.csv",
        "data/report_paperformat_data.xml",
        "data/res_company_data.xml",
        "report/invoices_report.xml",
        "report/invoice_report_views.xml",
        "report/external_layout.xml",
        "report/external_layout_bold.xml",
        "report/external_layout_standard.xml",
        "report/report_invoice_document.xml",
        "report/report_saleorder_document.xml",
        "report/report_picking.xml",
        "report/report_payment_receipt_document.xml",
        "views/account_move_views.xml",
        "views/stock_move_views.xml",
        "views/mrp_production_views.xml",
        "views/product_category_views.xml",
        "views/product_template_views.xml",
        "views/sale_order_views.xml",
    ],
    "demo": [],
    "installable": True,
    "auto_install": False,
    "application": True,
}
